// <auto-generated />
namespace MedicalTansik.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_is_academic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_is_academic));
        
        string IMigrationMetadata.Id
        {
            get { return "202202200955518_add_is_academic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
