// <auto-generated />
namespace MedicalTansik.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class remove_grad_require : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_grad_require));
        
        string IMigrationMetadata.Id
        {
            get { return "202202161548095_remove_grad_require"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
