// <auto-generated />
namespace MedicalTansik.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class set_is_academic_false : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(set_is_academic_false));
        
        string IMigrationMetadata.Id
        {
            get { return "202202201002413_set_is_academic_false"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
