// <auto-generated />
namespace MedicalTansik.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_student_rank : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_student_rank));
        
        string IMigrationMetadata.Id
        {
            get { return "202204012317052_added_student_rank"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
